apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-11T05:02:29Z"
  generation: 3
  labels:
    app: prime-factor-app
  name: prime-factor-app
  namespace: default
  resourceVersion: "9915"
  selfLink: /apis/apps/v1/namespaces/default/deployments/prime-factor-app
  uid: 67d125ae-feac-4c91-9563-fa06d6484f56
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prime-factor-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prime-factor-app
    spec:
      containers:
      - image: gcr.io/airy-highlander-295209/primefactorapp:v1
        imagePullPolicy: IfNotPresent
        name: primefactorapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-11T05:03:19Z"
    lastUpdateTime: "2020-11-11T05:03:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-11-11T05:02:29Z"
    lastUpdateTime: "2020-11-11T05:03:19Z"
    message: ReplicaSet "prime-factor-app-55857bfbdc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
